<?php
$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset items <?php /* @noEscape */ echo $methodCode ?>" id="payment_form_<?php /* @noEscape */ echo $methodCode ?>" style="display: none">
    <div class="field number required">
        <label for="routingnumber" class="label"><span><?php echo $block->escapeHtml(__('RoutingNumber')) ?></span></label>
        <div class="control">
            <input type="text" id="routingnumber" name="payment[routingnumber]" title="<?php echo $block->escapeHtml(__('RoutingNumber')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $block->escapeHtml($block->getInfoData('RoutingNumber')) ?>" />
        </div>
    </div>
	<div class="field number required">
        <label for="accountnumber" class="label"><span><?php echo $block->escapeHtml(__('AccountNumber')) ?></span></label>
        <div class="control">
            <input type="text" id="accountnumber" name="payment[accountnumber]" title="<?php echo $block->escapeHtml(__('AccountNumber')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $block->escapeHtml($block->getInfoData('AccountNumber')) ?>" />
        </div>
    </div>
</fieldset>
